config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  resources :orders
  resources :line_items
  resources :carts
  get 'store/index'

  # get 'startup/index'
  namespace :api do
    namespace :v1 do
      resources :fruits, only: [:index, :create, :destroy, :update]
    end
  end

  resources :products do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    get :who_bought, on: :member
  end

  # root to: 'home#index'
  root :to => 'store#index', :as => 'store'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
  	current_item = line_items.find_by_product_id(product_id)
  	if current_item
  	  current_item.quantity += 1
  	else
  	 current_item = line_items.build(product_id: product_id, quantity: 1)
  	end
  	current_item
   end

   def total_price
     line_items.to_a.sum { |item| item.total_price }
   end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]


  def index
    @carts = Cart.all
  end

  def show
    begin
    @cart = Cart.find(params[:id]) 
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, notice: 'Invalid cart'
    else
      respond_to do |format|
        format.html #show.html.erb
        format.json {render json: @cart}
      end
    end
  end

  def new
    @cart = Cart.new
  end

  def edit
  end


  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to store_url, 
          notice: 'Cart was successfully created.' }
        format.json { render :show, 
          status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, 
          status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_url,
       notice: 'Cart is currently empty' }
      format.json { head :no_content }
    end
  end

  private
    def set_cart
      @cart = Cart.find(params[:id])
    end

    def cart_params
      params.permit(:title, :text)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div class="cart_title">Your Cart</div>
<table>
  <%= render(cart.line_items) %>
    <tr class="total_line">
      <td colspan="2">Total</td>
      <td class="total_cell">
        <%= number_to_currency(@cart.total_price) %>
      </td>
    </tr>
</table>
<div class='cart_buttons'>
<%= button_to new_order_path, class:"button button-border button-padding", method: :get do%>
  <i class="glyphicon glyphicon-shopping-cart"></i> Checkout
<% end %>

<%= button_to cart, class:"button button-border button-padding", method: :delete, confirm: 'Are you sure?' do %>
  <i class="glyphicon glyphicon-trash"></i> Empty cart
  <% end %>
</div>

app/views/carts/_form.html.erb
<%= simple_form_for(@cart) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path, class: "btn btn-info" %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

    <div>
    <% @carts.each do |cart| %>
        <%= link_to 'Show', cart %>
        <%= link_to 'Edit', edit_cart_path(cart) %>
        <%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' }%>
      </div>
    <% end %>
  </div>
<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path, class: "btn btn-info" %>

app/views/carts/show.html.erb
<% if notice %>
  <p id="notice">
    <%= notice %>
  </p>
  <% end %>
  <%= render @cart %>